// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var StyleSheet$BsReactNative = require("bs-react-native/src/styleSheet.js");

var styles = StyleSheet$BsReactNative.create({
      container: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.justifyContent(/* Center */2),
              /* :: */[
                Style$BsReactNative.alignItems(/* Center */2),
                /* [] */0
              ]
            ]
          ]),
      app: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.marginHorizontal(/* Auto */0),
            /* :: */[
              Style$BsReactNative.maxWidth(/* Pt */Block.__(0, [500])),
              /* [] */0
            ]
          ]),
      logo: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.height(/* Pt */Block.__(0, [80])),
            /* [] */0
          ]),
      header: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.padding(/* Pt */Block.__(0, [20])),
            /* [] */0
          ]),
      title: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontWeight(/* Bold */737455525),
            /* :: */[
              Style$BsReactNative.fontSize(/* Float */Block.__(0, [1.5])),
              /* :: */[
                Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [1])),
                /* :: */[
                  Style$BsReactNative.textAlign(/* Center */3),
                  /* [] */0
                ]
              ]
            ]
          ]),
      text: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.lineHeight(1.5),
            /* :: */[
              Style$BsReactNative.fontSize(/* Float */Block.__(0, [1.125])),
              /* :: */[
                Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [1])),
                /* :: */[
                  Style$BsReactNative.textAlign(/* Center */3),
                  /* [] */0
                ]
              ]
            ]
          ]),
      link: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.color(/* String */Block.__(0, ["#1B95E0"])),
            /* [] */0
          ]),
      code: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontFamily("monospace"),
            /* [] */0
          ])
    });

exports.styles = styles;
/* styles Not a pure module */
