// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var TextLink = require("./TextLink");

var make = TextLink.default;

exports.make = make;
/* make Not a pure module */
