// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function option_map(fn, opt_value) {
  if (opt_value !== undefined) {
    return Caml_option.some(Curry._1(fn, Caml_option.valFromOption(opt_value)));
  }
  
}

function $less$less(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

exports.option_map = option_map;
exports.$less$less = $less$less;
/* No side effect */
