// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Link = require("./Link.bs.js");
var Utils = require("./Utils.bs.js");
var Styles = require("./styles/Styles.bs.js");
var TextLink = require("./MooxRn/TextLink.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Image$BsReactNative = require("bs-react-native/src/components/image.js");

var component = ReasonReact.statelessComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles.styles.app), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles.styles.header), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                        ReasonReact.element(undefined, undefined, Image$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, /* contain */427065300, /* `Required */[
                                                    202657151,
                                                    require("./assets/logoUri.svg")
                                                  ], Caml_option.some(Styles.styles.logo), undefined, undefined, "React logo", undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[])),
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Hello world!"])),
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles.styles.title), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils.s("React Native for Web")])),
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles.styles.title), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Hello world!"]))
                                      ])),
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles.styles.text), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                        Utils.s("This is an example of an app built with"),
                                        ReasonReact.element(undefined, undefined, TextLink.make("https://github.com/facebook/create-react-app", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils.s("Create React App")])),
                                        ReasonReact.element(undefined, undefined, Link.make("https://github.com/facebook/create-react-app", /* array */[Utils.s("Create React App")])),
                                        Utils.s("and"),
                                        ReasonReact.element(undefined, undefined, TextLink.make("https://github.com/necolas/react-native-web", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils.s("React Native for Web")]))
                                      ])),
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles.styles.text), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                        Utils.s("To get started, edit"),
                                        ReasonReact.element(undefined, undefined, TextLink.make("https://codesandbox.io/s/q4qymyp2l6/", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(Styles.styles.code), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils.s("src/App.js")]))
                                      ]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children);
      }));

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
