// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Styles = require("./styles/Styles.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReactNative = require("react-native");

function Link(Props) {
  var href = Props.href;
  var style = Props.style;
  var value = Props.value;
  var linkStyle = style !== undefined ? /* :: */[
      Styles.styles.link,
      /* :: */[
        Caml_option.valFromOption(style),
        /* [] */0
      ]
    ] : Styles.styles.link;
  return React.createElement(ReactNative.Text, {
              onPress: (function (_e) {
                  ReactNative.Linking.openURL(href).then((function (param) {
                          return Promise.resolve((console.log("opened " + href), /* () */0));
                        }));
                  return /* () */0;
                }),
              style: linkStyle,
              value: value
            });
}

var make = Link;

exports.make = make;
/* react Not a pure module */
